---

# we sort by domain
#
- name: directory for {{ domain }}
  file:
    path: files/{{ domain }}
    state: directory

- name: kickstart file is up to date
  template:
    src: default.ks
    dest: files/{{ domain }}/{{ inventory_hostname_short }}.ks
  when: not bootstrap.external_bootstrap_file

- name: kickstart file is up to date
  template:
    src: "{{ bootstrap.external_kickstart_file }}"
    dest: files/{{ domain }}/{{ inventory_hostname_short }}.ks
  when: bootstrap.external_bootstrap_file
